import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { AlertTriangle, ArrowLeft, CalendarDays, CheckCircle2, CircleDollarSign, ClipboardList, Download, File, FileText, HeartPulse, Mail, MessageCircle, Pencil, Phone, Plus, ShieldCheck, Stethoscope, UserRoundCheck, X } from "lucide-react";
import { getClinicContext } from "@/lib/clinic-context";
import { todayInTimeZone } from "@/lib/date-time";
import { WorkspaceShell } from "@/components/workspace-shell";
import { PatientRecordDialogs } from "@/components/patient-record-dialogs";
import { PatientFileUploader } from "@/components/patient-file-uploader";
import { archiveMedicalAlert, archivePatientFile, verifyMedicalAlert } from "./actions";

const upperTeeth = [18,17,16,15,14,13,12,11,21,22,23,24,25,26,27,28];
const lowerTeeth = [48,47,46,45,44,43,42,41,31,32,33,34,35,36,37,38];
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const date = new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" });
const clinicalRoles = new Set(["owner", "admin", "dentist", "assistant"]);
const patientEditorRoles = new Set(["owner", "admin", "dentist", "assistant", "secretary"]);
const savedMessages: Record<string, string> = { patient: "Dados cadastrais atualizados.", alert: "Alerta clínico registrado.", anamnesis: "Anamnese concluída e preservada no histórico.", odontogram: "Registro adicionado ao odontograma.", evolution: "Evolução clínica registrada." };
const errorMessages: Record<string, string> = { forbidden: "Seu perfil possui acesso somente para consulta.", invalid_name: "Informe um nome válido.", invalid_cpf: "O CPF informado é inválido.", duplicate_cpf: "Este CPF já pertence a outro paciente.", invalid_phone: "Confira o telefone informado.", invalid_postal_code: "O CEP deve ter oito números.", invalid_state: "Informe uma UF válida.", invalid_birth_date: "Confira a data de nascimento.", invalid_alert: "Preencha corretamente o alerta.", invalid_anamnesis: "Responda todos os itens obrigatórios da anamnese.", invalid_odontogram: "Confira o dente FDI e a descrição clínica.", invalid_evolution: "Confira data, horário e descrição da evolução.", save_failed: "Não foi possível salvar. Tente novamente." };
const alertLabels: Record<string, string> = { allergy: "Alergia", medication: "Medicamento", condition: "Condição sistêmica", bleeding: "Sangramento", cardiac: "Cardíaco", other: "Outro" };
const fileLabels: Record<string, string> = { intraoral_photo: "Foto intraoral", radiograph: "Radiografia", exam: "Exame", document: "Documento", other: "Outro" };

function formatPhone(value: string | null) { if (!value) return "Não informado"; const digits = value.replace(/\D/g, "").replace(/^55/, ""); return digits.length === 11 ? `(${digits.slice(0,2)}) ${digits.slice(2,7)}-${digits.slice(7)}` : value; }
function formatCpf(value: string | null) { return value?.length === 11 ? `${value.slice(0,3)}.${value.slice(3,6)}.${value.slice(6,9)}-${value.slice(9)}` : value || "Não informado"; }
function statusLabel(status: string) { return ({ draft:"Rascunho", pending:"Aguardando aprovação", partially_approved:"Aprovado parcialmente", approved:"Aprovado", cancelled:"Cancelado", open:"Em aberto", partially_paid:"Pago parcialmente", paid:"Pago", awaiting_settlement:"Aguardando repasse", settled:"Liquidado", reversed:"Estornado", final:"Finalizada", signed:"Assinada", voided:"Anulada", diagnosis:"Diagnóstico", condition:"Condição", planned_procedure:"Planejado", executed_procedure:"Executado" } as Record<string,string>)[status] ?? status; }
function formatBytes(value: number) { return value < 1024 * 1024 ? `${Math.ceil(value / 1024)} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`; }

export default async function PatientRecordPage({ params, searchParams }: { params: Promise<{ publicId: string }>; searchParams: Promise<{ panel?: string; saved?: string; error?: string }> }) {
  const context = await getClinicContext();
  if (!context) redirect("/onboarding");
  const [{ publicId }, query] = await Promise.all([params, searchParams]);
  const { data: patient } = await context.supabase.from("patients").select("*").eq("clinic_id", context.clinic.id).eq("public_id", publicId).is("deleted_at", null).maybeSingle();
  if (!patient) notFound();
  const { data: template } = await context.supabase.from("anamnesis_templates").select("id, name, version").eq("clinic_id", context.clinic.id).eq("active", true).is("deleted_at", null).order("version", { ascending: false }).limit(1).maybeSingle();
  const [alertsResult, evolutionsResult, budgetsResult, installmentsResult, odontogramResult, anamnesesResult, questionsResult, filesResult, profilesResult] = await Promise.all([
    context.supabase.from("patient_medical_alerts").select("id, public_id, alert_type, description, severity, verified_at").eq("patient_id", patient.id).eq("active", true).is("deleted_at", null).order("severity"),
    context.supabase.from("clinical_evolutions").select("id, public_id, professional_profile_id, description, occurred_at, status, signed_at, is_automatic").eq("patient_id", patient.id).is("deleted_at", null).order("occurred_at", { ascending: false }).limit(20),
    context.supabase.from("budgets").select("id, public_id, description, status, total_amount, discount_amount, issued_at").eq("patient_id", patient.id).is("deleted_at", null).order("issued_at", { ascending: false }).limit(5),
    context.supabase.from("installments").select("id, amount, paid_amount, settled_amount, due_date, status, sequence_number, total_installments").eq("patient_id", patient.id).is("deleted_at", null).order("due_date", { ascending: false }).limit(12),
    context.supabase.from("odontogram_entries").select("id, public_id, tooth_code, tooth_set, surfaces, entry_kind, status, description, occurred_at, recorded_by").eq("patient_id", patient.id).is("deleted_at", null).order("occurred_at", { ascending: false }),
    context.supabase.from("patient_anamneses").select("id, public_id, completed_at, created_at, answered_by_patient, answered_by_profile_id").eq("patient_id", patient.id).is("deleted_at", null).order("created_at", { ascending: false }).limit(1),
    template ? context.supabase.from("anamnesis_questions").select("id, public_id, position, prompt, required").eq("template_id", template.id).is("deleted_at", null).order("position") : Promise.resolve({ data: [], error: null }),
    context.supabase.from("patient_files").select("id, public_id, storage_path, original_name, mime_type, size_bytes, category, description, uploaded_by, created_at").eq("patient_id", patient.id).is("deleted_at", null).order("created_at", { ascending: false }),
    context.supabase.from("profiles").select("id, full_name").is("deleted_at", null),
  ]);
  const alerts = alertsResult.data ?? [], evolutions = evolutionsResult.data ?? [], budgets = budgetsResult.data ?? [], installments = installmentsResult.data ?? [], odontogram = odontogramResult.data ?? [], questions = questionsResult.data ?? [], files = filesResult.data ?? [];
  const latestAnamnesis = anamnesesResult.data?.[0];
  const profileById = new Map((profilesResult.data ?? []).map((profile) => [profile.id, profile.full_name]));
  const { data: priorAnswers } = latestAnamnesis ? await context.supabase.from("anamnesis_answers").select("question_id, selection, answer_text").eq("patient_anamnesis_id", latestAnamnesis.id).is("deleted_at", null) : { data: [] };
  const answerQuestionIds = Object.fromEntries(questions.map((question) => [question.id, question.public_id]));
  const signedResult = files.length ? await context.supabase.storage.from("clinical-files").createSignedUrls(files.map((item) => item.storage_path), 3600) : { data: [] };
  const signedByPath = new Map<string, string>((signedResult.data ?? []).flatMap((item) => item.signedUrl ? [[item.path, item.signedUrl] as [string, string]] : []));
  const outstanding = installments.filter((item) => ["open","partially_paid","awaiting_settlement"].includes(item.status)).reduce((sum, item) => sum + Number(item.amount) - Number(item.paid_amount), 0);
  const approvedBudget = budgets.filter((item) => item.status === "approved" || item.status === "partially_approved").reduce((sum, item) => sum + Number(item.total_amount), 0);
  const teethWithEntry = new Map<number, (typeof odontogram)[number]>();
  odontogram.filter((entry) => entry.tooth_set === "permanent").forEach((entry) => { if (entry.tooth_code && !teethWithEntry.has(entry.tooth_code)) teethWithEntry.set(entry.tooth_code, entry); });
  const displayName = patient.social_name || patient.full_name;
  const canClinicalEdit = clinicalRoles.has(context.role), canEditPatient = patientEditorRoles.has(context.role);
  const today = todayInTimeZone(context.clinic.timezone);
  const currentTime = new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit", hour12: false, timeZone: context.clinic.timezone }).format(new Date());
  const verifyAlert = verifyMedicalAlert.bind(null, publicId), archiveAlert = archiveMedicalAlert.bind(null, publicId), archiveFile = archivePatientFile.bind(null, publicId);
  const toothRow = (teeth: number[]) => <div className="grid grid-cols-8 gap-1.5 sm:grid-cols-16">{teeth.map((tooth) => { const entry = teethWithEntry.get(tooth); return <div key={tooth} title={entry?.description ?? `Dente ${tooth} sem registro`} className={`grid aspect-square min-h-9 place-items-center rounded-lg border text-[11px] font-semibold ${entry ? entry.entry_kind === "executed_procedure" ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-amber-300 bg-amber-50 text-amber-800" : "border-[#dce2df] bg-white text-[#72807b]"}`}>{tooth}</div>; })}</div>;

  return <WorkspaceShell clinicName={context.clinic.trade_name} userName={context.profile.full_name}><main>
    <header className="flex min-h-[68px] items-center gap-3 border-b border-[#dce2df] bg-white px-4 sm:px-6"><Link href="/patients" className="grid h-9 w-9 place-items-center rounded-xl border border-[#dce2df] text-[#63716c]" aria-label="Voltar"><ArrowLeft size={17} /></Link><div className="min-w-0"><p className="truncate text-sm font-semibold">{displayName}</p><p className="text-xs text-[#7a8581]">Prontuário integrado</p></div><div className="ml-auto flex gap-2"><a href={patient.whatsapp_e164 ? `https://wa.me/${patient.whatsapp_e164.replace(/\D/g, "")}` : "#"} target={patient.whatsapp_e164 ? "_blank" : undefined} rel="noreferrer" aria-disabled={!patient.whatsapp_e164} className={`hidden h-10 items-center gap-2 rounded-xl border border-[#dce2df] bg-white px-3.5 text-sm font-semibold text-[#52605b] sm:flex ${!patient.whatsapp_e164 ? "pointer-events-none opacity-40" : ""}`}><MessageCircle size={16} />WhatsApp</a><Link href={`/agenda?patient=${patient.public_id}&new=1`} className="flex h-10 items-center gap-2 rounded-xl bg-[#176b55] px-3.5 text-sm font-semibold text-white"><CalendarDays size={16} />Agendar</Link></div></header>
    <section className="p-4 sm:p-6 lg:p-7">
      {query.saved && savedMessages[query.saved] ? <div className="mb-4 flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><CheckCircle2 size={17} />{savedMessages[query.saved]}</div> : null}
      {query.error && errorMessages[query.error] ? <div className="mb-4 flex items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800"><AlertTriangle size={17} />{errorMessages[query.error]}</div> : null}
      {!canClinicalEdit ? <div className="mb-4 flex items-center gap-2 rounded-xl border border-sky-200 bg-sky-50 px-4 py-3 text-sm text-sky-800"><ShieldCheck size={17} />Modo de auditoria: prontuário disponível para consulta, sem permissão de alteração.</div> : null}
      <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="min-w-0 space-y-4">
        <article className="rounded-2xl border border-[#dce2df] bg-white p-5 sm:p-6"><div className="flex flex-wrap items-start gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-[#e7f1ed] text-lg font-bold text-[#176b55]">{displayName.split(" ").slice(0,2).map((part) => part[0]).join("")}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-[-.04em]">{displayName}</h1><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.08em] text-emerald-700">Ativo</span></div>{patient.social_name ? <p className="mt-1 text-xs text-[#7a8581]">Nome civil: {patient.full_name}</p> : null}<div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs text-[#62706b]"><span className="flex items-center gap-1.5"><Phone size={14} />{formatPhone(patient.phone_e164)}</span><span className="flex items-center gap-1.5"><MessageCircle size={14} />{formatPhone(patient.whatsapp_e164)}</span><span className="flex items-center gap-1.5"><Mail size={14} />{patient.email || "E-mail não informado"}</span></div></div>{canEditPatient ? <Link href="?panel=edit" className="grid h-9 w-9 place-items-center rounded-xl border border-[#dce2df] text-[#61706b]" aria-label="Editar cadastro"><Pencil size={16} /></Link> : null}</div></article>
        <article className={`rounded-2xl border p-5 ${alerts.some((alert) => alert.severity === "critical") ? "border-rose-200 bg-rose-50" : "border-amber-200 bg-amber-50"}`}><div className="flex items-center gap-2"><AlertTriangle size={18} /><h2 className="text-sm font-semibold">Alertas antes do atendimento</h2>{canClinicalEdit ? <Link href="?panel=alert" className="ml-auto flex items-center gap-1 rounded-lg bg-white/80 px-2.5 py-1.5 text-xs font-semibold"><Plus size={14} />Adicionar</Link> : null}</div>{alerts.length ? <div className="mt-3 grid gap-2 sm:grid-cols-2">{alerts.map((alert) => <div key={alert.id} className="rounded-xl border border-current/10 bg-white/70 p-3"><div className="flex items-center gap-2"><p className="text-xs font-semibold">{alertLabels[alert.alert_type] ?? alert.alert_type}</p><span className={`ml-auto h-2 w-2 rounded-full ${alert.severity === "critical" ? "bg-rose-500" : alert.severity === "warning" ? "bg-amber-500" : "bg-sky-500"}`} /></div><p className="mt-1 text-xs leading-5 opacity-75">{alert.description}</p><div className="mt-3 flex items-center gap-2"><span className="text-[10px] font-medium opacity-60">{alert.verified_at ? "Verificado" : "Aguardando verificação"}</span>{canClinicalEdit && !alert.verified_at ? <form action={verifyAlert} className="ml-auto"><input type="hidden" name="alert_public_id" value={alert.public_id} /><button className="text-[10px] font-bold text-[#176b55]">Verificar</button></form> : null}{canClinicalEdit ? <form action={archiveAlert}><input type="hidden" name="alert_public_id" value={alert.public_id} /><button className="grid h-6 w-6 place-items-center" aria-label="Arquivar alerta"><X size={13} /></button></form> : null}</div></div>)}</div> : <p className="mt-3 text-xs opacity-65">Nenhum alerta médico ativo.</p>}</article>
        <nav className="flex gap-2 overflow-x-auto rounded-2xl border border-[#dce2df] bg-white p-2 text-xs font-semibold text-[#62706b]">{[["#odontograma","Odontograma"],["#evolucao","Evolução"],["#anamnese","Anamnese"],["#arquivos","Arquivos"],["#orcamentos","Orçamentos"],["#financeiro","Financeiro"]].map(([href,label]) => <a href={href} key={href} className="whitespace-nowrap rounded-xl px-3 py-2 hover:bg-[#edf3f0] hover:text-[#176b55]">{label}</a>)}</nav>
        <article id="odontograma" className="scroll-mt-4 rounded-2xl border border-[#dce2df] bg-white p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">Odontograma permanente</p><p className="mt-1 text-xs text-[#7a8581]">Leitura rápida pela numeração FDI e registro por faces.</p></div>{canClinicalEdit ? <Link href="?panel=odontogram" className="flex items-center gap-1.5 rounded-xl border border-[#dce2df] px-3 py-2 text-xs font-semibold"><Plus size={14} />Registrar</Link> : null}</div><div className="mt-6 space-y-2">{toothRow(upperTeeth)}<div className="border-t border-dashed border-[#d8dfdc]" />{toothRow(lowerTeeth)}</div><div className="mt-5 flex flex-wrap gap-4 text-[11px] text-[#697670]"><span className="flex items-center gap-1.5"><i className="h-2.5 w-2.5 rounded bg-amber-200" />Condição ou planejamento</span><span className="flex items-center gap-1.5"><i className="h-2.5 w-2.5 rounded bg-emerald-200" />Procedimento executado</span></div>{odontogram.length ? <div className="mt-5 border-t border-[#edf0ee] pt-4"><p className="mb-2 text-xs font-semibold text-[#52605b]">Registros recentes</p>{odontogram.slice(0,4).map((entry) => <div key={entry.id} className="flex gap-3 border-b border-[#edf0ee] py-2.5 last:border-0"><span className="rounded-lg bg-[#edf3f0] px-2 py-1 text-[10px] font-bold text-[#176b55]">{entry.tooth_code ? `D${entry.tooth_code}` : "Arco"}</span><span className="min-w-0 flex-1 text-xs"><span className="block truncate font-medium">{entry.description}</span><span className="mt-0.5 block text-[10px] text-[#84908b]">{statusLabel(entry.entry_kind)} · {date.format(new Date(entry.occurred_at))}</span></span></div>)}</div> : null}</article>
        <article id="evolucao" className="scroll-mt-4 rounded-2xl border border-[#dce2df] bg-white"><div className="flex items-center justify-between border-b border-[#e7ebe9] px-5 py-4 sm:px-6"><div><p className="text-sm font-semibold">Evolução clínica</p><p className="mt-1 text-xs text-[#7a8581]">Linha do tempo imutável após assinatura</p></div>{canClinicalEdit ? <Link href="?panel=evolution" className="flex items-center gap-1.5 rounded-xl bg-[#17201d] px-3 py-2 text-xs font-semibold text-white"><Plus size={14} />Nova evolução</Link> : null}</div>{evolutions.length ? evolutions.map((evolution) => <div key={evolution.id} className="flex gap-4 border-b border-[#edf0ee] px-5 py-4 last:border-0 sm:px-6"><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${evolution.status === "signed" ? "bg-emerald-500" : "bg-slate-300"}`} /><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><p className="text-xs font-semibold text-[#52605b]">{date.format(new Date(evolution.occurred_at))} · {profileById.get(evolution.professional_profile_id) ?? "Profissional"}</p><span className="text-[10px] font-semibold uppercase text-[#84908b]">{statusLabel(evolution.status)}</span></div><p className="mt-2 whitespace-pre-line text-sm leading-6 text-[#35423e]">{evolution.description}</p></div></div>) : <div className="p-8 text-center text-sm text-[#7a8581]">Nenhuma evolução clínica registrada.</div>}</article>
        <article id="anamnese" className="scroll-mt-4 rounded-2xl border border-[#dce2df] bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl ${latestAnamnesis ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}><UserRoundCheck size={19} /></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">Anamnese clínica</p><p className="mt-1 text-xs leading-5 text-[#7a8581]">{latestAnamnesis ? `Concluída em ${date.format(new Date(latestAnamnesis.completed_at || latestAnamnesis.created_at))}${latestAnamnesis.answered_by_patient ? " · respondida pelo paciente" : ""}` : "Ainda não preenchida. Conclua antes do primeiro procedimento."}</p></div>{canClinicalEdit && questions.length ? <Link href="?panel=anamnesis" className="rounded-xl border border-[#dce2df] px-3 py-2 text-xs font-semibold">{latestAnamnesis ? "Revisar" : "Preencher"}</Link> : null}</div>{latestAnamnesis && priorAnswers?.length ? <div className="mt-4 grid gap-2 sm:grid-cols-2">{priorAnswers.filter((answer) => answer.selection === "yes" || answer.answer_text).slice(0,6).map((answer) => <div key={answer.question_id} className="rounded-xl bg-[#f7f9f8] p-3 text-xs"><p className="font-semibold text-[#52605b]">{questions.find((q) => q.id === answer.question_id)?.prompt}</p><p className="mt-1 text-[#71807b]">{answer.selection === "yes" ? "Sim" : answer.selection === "no" ? "Não" : "Não sabe"}{answer.answer_text ? ` · ${answer.answer_text}` : ""}</p></div>)}</div> : null}</article>
        <article id="arquivos" className="scroll-mt-4 rounded-2xl border border-[#dce2df] bg-white p-5 sm:p-6"><div><p className="text-sm font-semibold">Exames e arquivos clínicos</p><p className="mt-1 text-xs text-[#7a8581]">Fotos intraorais, radiografias, exames e documentos em armazenamento privado.</p></div>{canClinicalEdit ? <PatientFileUploader patientPublicId={publicId} clinicId={context.clinic.id} /> : null}{files.length ? <div className="mt-4 grid gap-2 sm:grid-cols-2">{files.map((item) => <div key={item.id} className="flex items-center gap-3 rounded-xl border border-[#e3e8e5] p-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#edf3f0] text-[#176b55]"><File size={16} /></span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold">{item.original_name}</span><span className="mt-0.5 block text-[10px] text-[#84908b]">{fileLabels[item.category] ?? item.category} · {formatBytes(item.size_bytes)}</span></span>{signedByPath.get(item.storage_path) ? <a href={signedByPath.get(item.storage_path)} target="_blank" rel="noreferrer" className="grid h-8 w-8 place-items-center rounded-lg" aria-label="Abrir arquivo"><Download size={15} /></a> : null}{canClinicalEdit ? <form action={archiveFile}><input type="hidden" name="file_public_id" value={item.public_id} /><button className="grid h-8 w-8 place-items-center rounded-lg" aria-label="Arquivar arquivo"><X size={14} /></button></form> : null}</div>)}</div> : <p className="mt-4 rounded-xl bg-[#f7f9f8] p-5 text-center text-xs text-[#7a8581]">Nenhum arquivo anexado.</p>}</article>
        <div className="grid gap-4 lg:grid-cols-2"><article id="orcamentos" className="rounded-2xl border border-[#dce2df] bg-white"><div className="flex items-center justify-between border-b border-[#e7ebe9] px-5 py-4"><div><p className="text-sm font-semibold">Planos de tratamento</p><p className="mt-1 text-xs text-[#7a8581]">{money.format(approvedBudget)} aprovados</p></div><FileText size={18} className="text-[#89938f]" /></div>{budgets.length ? budgets.map((budget) => <div key={budget.id} className="flex items-center gap-3 border-b border-[#edf0ee] px-5 py-3.5 last:border-0"><ClipboardList size={17} className="text-[#176b55]" /><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold">{budget.description}</span><span className="text-[11px] text-[#7a8581]">{statusLabel(budget.status)}</span></span><span className="text-xs font-semibold">{money.format(Number(budget.total_amount))}</span></div>) : <div className="p-7 text-center text-xs text-[#7a8581]">Nenhum orçamento criado.</div>}</article><article id="financeiro" className="rounded-2xl border border-[#dce2df] bg-white"><div className="flex items-center justify-between border-b border-[#e7ebe9] px-5 py-4"><div><p className="text-sm font-semibold">Financeiro do paciente</p><p className="mt-1 text-xs text-[#7a8581]">{money.format(outstanding)} em aberto</p></div><CircleDollarSign size={18} className="text-[#89938f]" /></div>{installments.length ? installments.slice(0,5).map((installment) => <div key={installment.id} className="flex items-center gap-3 border-b border-[#edf0ee] px-5 py-3.5"><span className={`h-2.5 w-2.5 rounded-full ${["settled","paid"].includes(installment.status) ? "bg-emerald-500" : "bg-amber-400"}`} /><span className="min-w-0 flex-1 text-xs font-semibold">Parcela {installment.sequence_number}/{installment.total_installments}</span><span className="text-xs font-semibold">{money.format(Number(installment.amount))}</span></div>) : <div className="p-7 text-center text-xs text-[#7a8581]">Sem parcelas vinculadas.</div>}</article></div>
      </div><aside className="space-y-4"><article className="rounded-2xl bg-[#17201d] p-5 text-white"><p className="text-sm font-semibold">Resumo assistencial</p><div className="mt-5 space-y-4">{[[HeartPulse,"Alertas médicos",String(alerts.length)],[Stethoscope,"Dentes com registro",String(teethWithEntry.size)],[FileText,"Evoluções clínicas",String(evolutions.length)],[CircleDollarSign,"Saldo em aberto",money.format(outstanding)]].map(([Icon,label,value]) => { const ItemIcon = Icon as typeof HeartPulse; return <div key={String(label)} className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/8"><ItemIcon size={17} /></span><span className="min-w-0 flex-1"><span className="block text-[11px] text-white/45">{String(label)}</span><span className="block truncate text-sm font-semibold">{String(value)}</span></span></div>; })}</div></article><article className="rounded-2xl border border-[#dce2df] bg-white p-5"><div className="flex items-center justify-between"><p className="text-sm font-semibold">Segurança clínica</p><ShieldCheck size={18} className="text-[#176b55]" /></div><div className="mt-4 space-y-3 text-xs"><p><CheckCircle2 size={15} className={`mr-2 inline ${latestAnamnesis ? "text-emerald-600" : "text-slate-300"}`} />{latestAnamnesis ? "Anamnese atualizada" : "Anamnese pendente"}</p><p><CheckCircle2 size={15} className={`mr-2 inline ${alerts.length === 0 || alerts.every((a) => a.verified_at) ? "text-emerald-600" : "text-amber-500"}`} />{alerts.length ? `${alerts.filter((a) => a.verified_at).length}/${alerts.length} alertas verificados` : "Sem alertas ativos"}</p></div></article><article className="rounded-2xl border border-[#dce2df] bg-white p-5"><p className="text-sm font-semibold">Dados cadastrais</p><dl className="mt-4 space-y-3 text-xs"><div className="flex justify-between gap-4"><dt className="text-[#7a8581]">Nascimento</dt><dd className="font-medium">{patient.birth_date ? date.format(new Date(`${patient.birth_date}T12:00:00`)) : "Não informado"}</dd></div><div className="flex justify-between gap-4"><dt className="text-[#7a8581]">CPF</dt><dd className="font-medium">{formatCpf(patient.cpf_digits)}</dd></div><div className="flex justify-between gap-4"><dt className="text-[#7a8581]">Cidade</dt><dd className="font-medium">{patient.city || "Não informada"}</dd></div></dl>{canEditPatient ? <Link href="?panel=edit" className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-[#dce2df] px-3 py-2.5 text-xs font-semibold"><Pencil size={14} />Editar cadastro</Link> : null}</article></aside></div>
    </section>
    {(canEditPatient || canClinicalEdit) ? <PatientRecordDialogs publicId={publicId} panel={query.panel} patient={patient} questions={questions} existingAnswers={priorAnswers ?? []} answerQuestionIds={answerQuestionIds} today={today} currentTime={currentTime} /> : null}
  </main></WorkspaceShell>;
}
